#!/bin/sh

## autoload vcs and colors
autoload -U colors && colors
autoload -Uz vcs_info

# enable only git 
zstyle ':vcs_info:*' enable git

# setup a hook that runs before every ptompt. 
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:git:*' formats " %{%F{11}%}[%b]%u%f" 

# format our main prompt for hostname and current folder
PROMPT="@%n %{$fg[blue]%}%1~"

# git branch name and unstaged checkmark
PROMPT+="\$vcs_info_msg_0_"
PROMPT+="%{$reset_color%} $ "
